### ISSUE TITLE
Intermixed output

### ISSUE THREAD

**Issue by lfos** [poolpOrg/filter-senderscore#10]
To the best of my knowledge, `fmt.Printf` is not guaranteed to be atomic and there is the (theoretical) possibility of intermixed output originating from the "delayed" goroutines. Two alternative solutions:

* Use a classical locking mechanism, such as a mutex, to make the output atomic.
* Create a separate routine with an infinite loop that reads from a Go channel and outputs the strings it recevies. In all the other routines, write to that channel instead of writing to stdout.

The second option is probably the "Go way" of implementing this. I'd be happy to implement either solution. Let me know what you think.

**Comment by lfos** [comment]
Also, since there will definitely be a lot of conflicts with PR #6, please let me know whether you'd like this to be fixed before you make a decision on #6 (and have that patch rebased) or whether you'd like to resolve #6 first and have this fixed on top.

**Comment by lfos** [comment]
Forget the previous comment. I found an elegant solution that fixes the issue and refactors at the same time, all in one small/atomic change.

**Comment by poolpOrg** [comment]
perfect, you were spot on.

when you send your second version of the diff, what bothered me was that you replaced the fmt.Printf() by a construct which produced two outputs / line and seemed concurrency unsafe to me (I relied on the fact that a single Printf call of small lengths like these would be written atomically to the underlying socketpair() but that's not really a good thing to do... you are right not to assume Printf to be atomic).

your synchronized output is the perfect solution.

**Comment by lfos** [comment]
Great!

It seems like filter-rspamd might be affacted by the same issue? I could provide a similar patch if you agree it's a good idea.

**Comment by poolpOrg** [comment]
On Wed, Dec 18, 2019 at 04:45:45AM -0800, Lukas Fleischer wrote:
> Great!
> 
> It seems like filter-rspamd might be affacted by the same issue? I could provide a similar patch if you agree it's a good idea.
> 

yes please, feel free to submit similar patch for other filters

I intended to do it on Friday when my holiday begins but if you
submit patches before, good for me :-)

**Comment by lfos** [comment]
Done! Unfortunately, I do not use any of the other filters, which makes testing much harder. The patches in my PRs are fully untested. Please make sure you test them before merging and let me know whether there's anything that needs to be changed!
