### ISSUE TITLE
Segfault on OpenBSD -current; needs rebuild with go 1.16

### ISSUE THREAD

**Issue by torarg** [poolpOrg/filter-senderscore#27]
#### Description
Probably since this commit https://github.com/openbsd/src/commit/570e619d6099ecbb649efb5d979ef48447241d1f the current build of filter-senderscore is segfaulting on OpenBSD -current:

```
www$ /usr/local/libexec/smtpd/filter-senderscore                                                                                                                 
Segmentation fault
```

Producing these dmesg entries:

```
www$ dmesg |grep filter\-sender
[filter-sendersco]14316/423618 pc=469206 inside 29c685000-29c692000: bogus syscall
[filter-sendersco]40021/251269 pc=469206 inside 225ed2000-225edf000: bogus syscall
[...]
```

Update: Forgot to attach versions:

```
www# pkg_info  opensmtpd-filter-senderscore 
Information for inst:opensmtpd-filter-senderscore-0.1.1

Comment:
SenderScore integration to the OpenSMTPD daemon

Description:
filter-senderscore is an opensmtpd filter that performs a DNS
lookup in the SenderScore registry to determine reputation of
an IP address and allow reputation-based blocking, junking or
delaying of sessions.

Maintainer: Gilles Chehade <gilles@poolp.org>

WWW: https://github.com/poolpOrg/filter-senderscore/


www# uname -a                               
OpenBSD  6.9 GENERIC#374 amd64
```

#### Solution
go1.16 does it's syscalls through libc[1], so just rebuilding with go1.16 solved this issue for me. If I'm not misunderstanding the ports Makefile, the binary is directly downloaded from here, so I hope this is the correct place for this issue.

[1] https://utcc.utoronto.ca/~cks/space/blog/programming/Go116OpenBSDUsesLibc

**Comment by qbit** [comment]
Everything got a bump earlier today - you should see new packages here pretty quick.

**Comment by poolpOrg** [comment]
The issue has been addressed for a while now, this ticket is no longer relevant, closing.
