### ISSUE TITLE
New package (version) of code containing allowedIPs

### ISSUE THREAD

**Issue by dwlfrth** [poolpOrg/filter-senderscore#30]
Hey there,
First of all, thanks for the time involved in all thoses projects that benefits to a lot of people.
Was wondering if it is possible to release a 0.12 version containing the allowedIP code ?
Currently running OpenSMTPd on Alpine but the filte-senderscore package is based on 0.11.
Also, it looks like Alpine package maintainer would not build a package on a "master" branch.

Cheers !

**Comment by poolpOrg** [comment]
I missed this, just did a release

**Comment by dwlfrth** [comment]
Cheers !
