### ISSUE TITLE
Retuning score=127 every time

### ISSUE THREAD

**Issue by felipebsd** [poolpOrg/filter-senderscore#31]
I don't know why senderscore is returning score = 127.

Aug 31 04:54:43 mailtest smtpd[5970]: senderscore: link-connect addr=184.105.139.67 score=127
Aug 31 05:12:37 mailtest smtpd[5970]: senderscore: link-connect addr=184.105.139.90 score=127
Aug 31 05:12:54 mailtest smtpd[5970]: senderscore: link-connect addr=184.105.139.118 score=127
Aug 31 09:09:04 mailtest smtpd[5970]: senderscore: link-connect addr=172.168.157.250 score=127
Aug 31 10:30:19 mailtest smtpd[5970]: senderscore: link-connect addr=201.159.185.94 score=127
Aug 31 10:30:32 mailtest smtpd[5970]: senderscore: link-connect addr=201.159.185.94 score=127
Aug 31 11:28:17 mailtest smtpd[69359]: senderscore: link-connect addr=177.47.151.62 score=127
Aug 31 11:29:05 mailtest smtpd[69359]: senderscore: link-connect addr=177.47.151.62 score=127
Aug 31 11:33:44 mailtest smtpd[83461]: senderscore: link-connect addr=177.47.151.62 score=127
Aug 31 12:20:43 mailtest smtpd[83461]: senderscore: link-connect addr=104.152.52.177 score=127
Aug 31 17:24:18 mailtest smtpd[83461]: senderscore: link-connect addr=62.60.190.7 score=127
Aug 31 20:57:18 mailtest smtpd[83461]: senderscore: link-connect addr=178.215.236.65 score=127
Aug 31 21:47:00 mailtest smtpd[83461]: senderscore: link-connect addr=64.62.197.26 score=127

Tests:
Fail: FreeBSD 14.1, opensmtpd-filter-senderscore-0.1.1_21 and opensmtpd-filter-senderscore-0.1.1_22
Ok: FreeBSD 13.3, opensmtpd-filter-senderscore-0.1.1_19

**Comment by felipebsd** [comment]
Looks like a DNS problem, not a bug. Thank you.

**Comment by poolpOrg** [comment]
I still should check that value doesn't exceed 100 and warn, will look into it
